// FETCH PRODUCT TYPES
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const TOGGLE_CART_OVERLAY = "TOGGLE_CART_OVERLAY";
export const LOAD_CURRENT_ITEM = "LOAD_CURRENT_ITEM";


export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const CLOSE_CART_OVERLAY = "CLOSE_CART_OVERLAY";
export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";

// SHOPPING TYPES
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADJUST_QTY = "ADJUST_QTY";
